swagger: "2.0"
info:
  version: "0.0.1"
  title: API iTrackFlight
host: dev.server.itrackf.raks.com.ua
basePath: /api
#
schemes:
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
